#!/bin/sh

#
# Copyright (c) 2021 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Find an MTD /dev file by name
findmtd() {
  m=$(grep -xl "$1" /sys/class/mtd/*/name)
  m=${m%/name}
  m=${m##*/}
  echo $m
}

#*UNUSEDrom_lists=(host-prime host-second vrom-prime vrom-second)
rom_lists=(host-prime host-second vrom-prime vrom-second)
rom_mtd_list=()

# Verify we can find all the needed host UEFI partitions
for f in "${rom_lists[@]}"
do
  echo "Checking for mtd partition ${f}"
  image=$(findmtd ${f})
  if test -z "$image"
  then
    echo "Unable to find mtd partition for ${f}"
    exit -1
  fi
  rom_mtd_list+=($image)
done

# Copy UEFI to shadow RAM
# host-prime to vrom-prime
echo "Copying UEFI image from /dev/${rom_mtd_list[0]} to /dev/${rom_mtd_list[2]}"
dd if=/dev/${rom_mtd_list[0]} of=/dev/${rom_mtd_list[2]}
#*UNUSED host-second to vrom-second
#*UNUSEDecho "Copying UEFI image from /dev/${rom_mtd_list[1]} to /dev/${rom_mtd_list[3]}"
#*UNUSEDdd if=/dev/${rom_mtd_list[1]} of=/dev/${rom_mtd_list[3]}
echo 0x1800008a > /sys/class/soc/srom/vromoff

# Parse the UEFI version info from the image and publish it to dbus
echo "Publishing HPE UEFI version information from /dev/${rom_mtd_list[2]} to /xyz/openbmc_project/software/bios_active"
uefi_version="$(hpe-uefi-version /dev/${rom_mtd_list[2]})"
busctl set-property xyz.openbmc_project.Software.BMC.Updater /xyz/openbmc_project/software/bios_active xyz.openbmc_project.Software.Version Version s "$uefi_version"
busctl get-property xyz.openbmc_project.Software.BMC.Updater /xyz/openbmc_project/software/bios_active xyz.openbmc_project.Software.Version Version
